import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Sidebar } from './components/layout/Sidebar';
import { CommandBar } from './components/layout/CommandBar';
import { SummaryStatsBar } from './components/outputs/SummaryStats/SummaryStatsBar';
import { PortfolioChart } from './components/outputs/PortfolioChart/PortfolioChart';
import { DetailTable } from './components/outputs/DetailTable/DetailTable';
import { useAppStore } from './store/useAppStore';
const App = () => {
    const { simulationResults } = useAppStore();
    const { manual, status } = simulationResults;
    return (_jsxs("div", { className: "flex h-screen w-full bg-slate-50 overflow-hidden font-sans text-slate-900", children: [_jsx(Sidebar, {}), _jsxs("main", { className: "flex-1 flex flex-col overflow-hidden", children: [_jsx(CommandBar, {}), _jsx("div", { className: "flex-1 overflow-y-auto p-8", children: _jsxs("div", { className: "w-full flex flex-col gap-8 pb-12", children: [_jsx(SummaryStatsBar, {}), status === 'idle' ? (_jsxs("div", { className: "bg-white rounded-xl border border-slate-200 shadow-sm p-12 flex flex-col items-center justify-center min-h-[500px]", children: [_jsx("div", { className: "w-16 h-16 bg-blue-50 text-blue-600 rounded-full flex items-center justify-center mb-6", children: _jsx("svg", { xmlns: "http://www.w3.org/2000/svg", className: "h-8 w-8", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" }) }) }), _jsx("h3", { className: "text-lg font-semibold text-slate-700 mb-2", children: "Ready to Simulate" }), _jsxs("p", { className: "text-slate-400 text-center max-w-sm", children: ["Configure your retirement parameters in the sidebar and click ", _jsx("strong", { className: "text-slate-600", children: "Run Simulation" }), " to see your financial forecast."] })] })) : status === 'running' ? (_jsxs("div", { className: "bg-white rounded-xl border border-slate-200 shadow-sm p-12 flex flex-col items-center justify-center min-h-[500px] animate-pulse", children: [_jsx("div", { className: "w-12 h-12 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mb-4" }), _jsx("p", { className: "text-slate-500 font-medium", children: "Calculating simulation..." })] })) : (_jsxs(_Fragment, { children: [_jsx(PortfolioChart, {}), _jsx(DetailTable, {})] })), !manual && status !== 'idle' && status !== 'running' && (_jsxs("div", { className: "p-4 bg-rose-50 border border-rose-100 text-rose-600 rounded-lg text-sm", children: [_jsx("p", { className: "font-bold mb-1", children: "Simulation Error" }), _jsx("p", { children: simulationResults.error || 'There was an error running the simulation. Please check your inputs and try again.' })] }))] }) })] })] }));
};
export default App;
